[package]
name = "abc221"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc221-a = { alias = "a", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_a" }
abc221-b = { alias = "b", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_b" }
abc221-c = { alias = "c", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_c" }
abc221-d = { alias = "d", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_d" }
abc221-e = { alias = "e", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_e" }
abc221-f = { alias = "f", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_f" }
abc221-g = { alias = "g", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_g" }
abc221-h = { alias = "h", problem = "https://atcoder.jp/contests/abc221/tasks/abc221_h" }

[[bin]]
name = "abc221-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc221-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc221-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc221-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc221-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc221-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc221-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc221-h"
path = "src/bin/h.rs"

[dependencies]
itertools = "0.11.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
